### ISSUE TITLE
grunt task

### ISSUE THREAD

**Issue by TrySound** [hail2u/postcss-single-charset#3]
Why need grunt task with dependency for such small plugin? Maybe for users better just add grunt-postcss?

**Comment by hail2u** [comment]
This small Grunt task can run (on Grunt v4) for evermore, and I think this PostCSS plugin may break on a future `grunt-postcss` that depends on PostCSS v5.

**Comment by TrySound** [comment]
Maybe better move it to another repo like `grunt-single-charset`?

**Comment by hail2u** [comment]
I’m too lazy to maintain separate repository.

**Comment by TrySound** [comment]
@hail2u You can create a repo and give me access. :)

**Comment by hail2u** [comment]
You can create on your own.

**Comment by TrySound** [comment]
And if i'll do, will you remove it from this package?

**Comment by hail2u** [comment]
I think there is no reason to remove it from repository.

**Comment by TrySound** [comment]
@hail2u My goal is to make cssnano smaller.

**Comment by hail2u** [comment]
`cssnano` has no interest for me.

**Comment by TrySound** [comment]
Why whole grunt task that need to write on disk and read again for such small plugin? It's useless and cumbersome. Also almost all plugins works with postcss@5. So it's problem of the plugins.

**Comment by TrySound** [comment]
https://github.com/TrySound/postcss-normalize-charset
